### ISSUE TITLE
Unable to create course in OLI course authoring platform

### ISSUE THREAD

**Issue by rkdasari** [Simon-Initiative/authoring-dev#24]
I followed the instructions and successfully configured OLI Course Authoring platform on Ubuntu 18.04. When I try to create a new course, I get an error
![Screenshot from 2019-05-13 01-19-47](https://user-images.githubusercontent.com/5461520/57597542-c3bdad80-751d-11e9-8d8b-f5c1c3a2b71d.jpg)
The actual cause of error is probably shown in one of the log messages below. I wanted to check if the error has anything to do with the installation glitches

```
authoring-server    | Caused by: org.keycloak.authorization.client.util.HttpResponseException: Unexpected response from server: 400 / Bad Request / Response from server: {"error":"unauthorized_client","error_description":"Invalid client secret"}
oli-keycloak        | 05:06:42,540 WARN  [org.keycloak.events] (default task-13) type=CLIENT_LOGIN_ERROR, realmId=oli_security, clientId=content_service, userId=null, ipAddress=172.18.0.9, error=invalid_client_credentials, grant_type=client_credentials
authoring-server    | 05:06:42,584 ERROR [org.jboss.as.ejb3.invocation] (EE-ManagedThreadFactory-default-Thread-1) WFLYEJB0034: EJB Invocation failed on component ContentPackageManager for method public com.google.gson.JsonElement edu.cmu.oli.content.boundary.managers.ContentPackageManager.createPackage(edu.cmu.oli.content.security.AppSecurityContext,com.google.gson.JsonObject): javax.ejb.EJBException: java.lang.RuntimeException: Could not find resource
```
Here is the full log picture

![Screenshot from 2019-05-13 00-58-25](https://user-images.githubusercontent.com/5461520/57597671-565e4c80-751e-11e9-990b-71c7dde6abc6.png)

**Comment by darrensiegel** [comment]
We have landed a fix for this in the authoring-sever repository. 

The fix here was to substitute the actual keycloak (development environment only) secret with the placeholder 'xxxxx' that was specified. 

Please try pulling master on authoring-sever, then "docker-compose down" and "docker-compose up --build" to redeploy the dev environment.
