### ISSUE TITLE
[FEATURE] Provide instructions for production environment setup

### ISSUE THREAD

**Issue by fkohrt** [Simon-Initiative/authoring-dev#34]
The [setup instructions](https://github.com/Simon-Initiative/authoring-dev/blob/6e609de/docs/setup.md) currently available are only targeting development setups. Adding instructions on how to setup a production enviroment would be of considerable value.

**Comment by darrensiegel** [comment]
Thanks for your interest in this project and for filing this issue.

It is worth mentioning that this project and its related projects (`authoring-client`, `authoring-server`, `authoring-admin`) represent one-half of a curriculum authoring and delivery system, specifically the authoring portion.  The delivery portion is not available as an open source project. 

Both the authoring and delivery portions of OLI are no longer under active development. They are in more of a maintenance mode as we have shifted our resources and efforts towards our next generation system _Torus_ (https://github.com/Simon-Initiative/oli-torus).  

The _Torus_ project is a combined curriculum authoring and delivery system, and is being developed entirely open source. It is easier to set up a development environment and easier to deploy in production, supports LTI 1.3, and is a more easily extensible system with regards to custom third-party activity development.  There is a publicly available product roadmap in that project's GitHub. 

I would encourage you to look at Torus to see if it meets the use cases that drew you to `authoring-dev`.  Feel free to contact me directly with any questions regarding Torus.  `darrensiegel` `at` `cmu` `dot` `edu`.

**Comment by fkohrt** [comment]
>  The delivery portion is not available as an open source project.

I see, thanks for the quick response!

> Both the authoring and delivery portions of OLI are no longer under active development. They are in more of a maintenance mode as we have shifted our resources and efforts towards our next generation system Torus (https://github.com/Simon-Initiative/oli-torus).

Maybe add that to the repo descriptions? I guess #32 and #33 don't matter that much to me then.

> The Torus project is a combined curriculum authoring and delivery system, and is being developed entirely open source. It is easier to set up a development environment and easier to deploy in production, supports LTI 1.3, and is a more easily extensible system with regards to custom third-party activity development. There is a publicly available product roadmap in that project's GitHub.

Cool, I will have a look!

> Feel free to contact me directly with any questions regarding Torus.

Thanks, will do :)
